2024-04-13 13:54:50.751 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-13 13:54:50.760 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-13 13:54:50.761 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-13 13:55:01.754 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-13 13:55:01.754 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-13 13:55:01.755 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-13 13:55:01.755 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-13 13:55:01.755 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-13 13:55:01.755 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-13 13:55:01.755 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-13 13:55:01.755 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-13 13:55:01.755 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-13 13:55:01.756 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-13 13:55:01.756 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-13 13:55:01.756 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-13 15:44:52.021 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 16:23:44.902 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 16:46:24.312 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 16:57:25.997 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 17:01:01.095 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 17:01:05.731 | WARNING  | __main__:start_record:1322 - 错误信息: Command '['ffmpeg', '-y', '-v', 'verbose', '-rw_timeout', '30000000', '-loglevel', 'error', '-hide_banner', '-user_agent', 'Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G973U) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36', '-protocol_whitelist', 'rtmp,crypto,file,http,https,tcp,tls,udp,rtp', '-thread_queue_size', '1024', '-analyzeduration', '20000000', '-probesize', '10000000', '-fflags', '+discardcorrupt', '-i', 'http://pull-hls-l11.douyincdn.com/stage/stream-403187777916108945_ld.m3u8?expire=1713603660&sign=4c89908cbf85f1b7ef7524bd16b0698b', '-bufsize', '8000k', '-sn', '-dn', '-reconnect_delay_max', '60', '-reconnect_streamed', '-reconnect_at_eof', '-max_muxing_queue_size', '1024', '-correct_ts_overflow', '1', '-c:v', 'copy', '-c:a', 'copy', '-map', '0', '-f', 'mpegts', 'D:/git/DouyinLiveRecorder/downloads/抖音直播/长沙刑事律师李俊杰/长沙刑事律师李俊杰_2024-04-13_17-01-01.ts']' returned non-zero exit status 1. 发生错误的行数: 1314
2024-04-13 17:21:19.632 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 17:28:21.781 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 21:25:19.506 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-13 21:31:41.340 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-13 21:31:41.340 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-13 21:31:41.341 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-13 22:15:11.448 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-13 22:15:11.448 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-13 22:15:11.449 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-14 00:38:49.510 | WARNING  | utils:wrapper:18 - 错误信息: type: JSONDecodeError, Expecting value: line 1 column 1 (char 0) in function get_douyin_stream_data at line: 355
2024-04-14 00:38:49.511 | WARNING  | utils:wrapper:18 - 错误信息: type: AttributeError, 'list' object has no attribute 'get' in function get_douyin_stream_url at line: 275
2024-04-14 00:38:49.511 | WARNING  | __main__:start_record:1345 - 错误信息: 'list' object has no attribute 'get' 发生错误的行数: 974
2024-04-14 01:24:31.357 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-14 08:46:48.704 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-14 09:21:50.912 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-14 09:21:56.924 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
2024-04-14 10:29:46.615 | WARNING  | utils:wrapper:18 - 错误信息: type: ValueError, unknown url type: '' in function dingtalk at line: 373
